import type { ToneTheme } from "./types";

export const TONES: Record<string, ToneTheme> = {
  trust: {
    id: "trust",
    name: "信頼・プロフェッショナル",
    primary: "#1B2A4A",
    accent: "#C9A84C",
    bgDark: "#0D1522",
    bgLight: "#F4F6FA",
    textPrimary: "#FFFFFF",
    textSecondary: "#B8C4D8",
    gradientStart: "#1B2A4A",
    gradientEnd: "#0D1522",
  },
  pop: {
    id: "pop",
    name: "ポップ・エネルギッシュ",
    primary: "#FF3366",
    accent: "#FFD700",
    bgDark: "#1A0A1E",
    bgLight: "#FFF5F8",
    textPrimary: "#FFFFFF",
    textSecondary: "#FFB8CC",
    gradientStart: "#FF3366",
    gradientEnd: "#FF6B35",
  },
  brand: {
    id: "brand",
    name: "ブランドカラー",
    primary: "#FF6B35",
    accent: "#2EC4B6",
    bgDark: "#1A0800",
    bgLight: "#FFF8F5",
    textPrimary: "#FFFFFF",
    textSecondary: "#FFB899",
    gradientStart: "#FF6B35",
    gradientEnd: "#2EC4B6",
  },
  nature: {
    id: "nature",
    name: "ナチュラル・オーガニック",
    primary: "#2D6A4F",
    accent: "#D4A373",
    bgDark: "#0A1F14",
    bgLight: "#F0F7F4",
    textPrimary: "#FFFFFF",
    textSecondary: "#A7C4B5",
    gradientStart: "#2D6A4F",
    gradientEnd: "#1B4332",
  },
  tech: {
    id: "tech",
    name: "テック・先進的",
    primary: "#6C63FF",
    accent: "#00D9FF",
    bgDark: "#0A0A1A",
    bgLight: "#F0F0FF",
    textPrimary: "#FFFFFF",
    textSecondary: "#A8A3FF",
    gradientStart: "#6C63FF",
    gradientEnd: "#0A0A1A",
  },
  luxury: {
    id: "luxury",
    name: "ラグジュアリー・高級",
    primary: "#1A1A2E",
    accent: "#E0B050",
    bgDark: "#0F0F1A",
    bgLight: "#FAF8F0",
    textPrimary: "#FFFFFF",
    textSecondary: "#C0A870",
    gradientStart: "#1A1A2E",
    gradientEnd: "#16213E",
  },
};
