import type { TemplateMetadata, BGMOption } from "../remotion/types";

export const TEMPLATE_REGISTRY: Record<string, TemplateMetadata> = {
  "01": {
    id: "01",
    name: "商品紹介（シンプル）",
    nameEn: "Product Introduction",
    description: "商品やサービスをシンプルに魅力的に紹介する王道テンプレート",
    category: "商品紹介",
    sceneCount: 5,
    fields: [
      { key: "catchcopy", label: "キャッチコピー", type: "text", required: true, placeholder: "あなたの毎日をもっと特別に", maxLength: 30 },
      { key: "subcopy", label: "サブコピー", type: "text", required: false, placeholder: "新しい体験をお届けします", maxLength: 40 },
      { key: "productImage", label: "商品画像", type: "image", required: false },
      { key: "feature1", label: "特徴1", type: "text", required: true, placeholder: "高品質な素材", maxLength: 20 },
      { key: "feature2", label: "特徴2", type: "text", required: true, placeholder: "安心の国内製造", maxLength: 20 },
      { key: "feature3", label: "特徴3", type: "text", required: true, placeholder: "送料無料", maxLength: 20 },
      { key: "stat", label: "実績数値", type: "text", required: false, placeholder: "累計10万個突破", maxLength: 20 },
      { key: "ctaText", label: "CTAテキスト", type: "text", required: true, placeholder: "今すぐチェック", maxLength: 15, defaultValue: "今すぐチェック" },
    ],
  },
  "02": {
    id: "02",
    name: "セール・キャンペーン告知",
    nameEn: "Sale Campaign",
    description: "期間限定セールやキャンペーンを印象的に告知するテンプレート",
    category: "セール",
    sceneCount: 5,
    fields: [
      { key: "saleTitle", label: "セールタイトル", type: "text", required: true, placeholder: "MEGA SALE", maxLength: 20 },
      { key: "discountText", label: "割引内容", type: "text", required: true, placeholder: "最大70%OFF", maxLength: 15 },
      { key: "productImage", label: "商品画像", type: "image", required: false },
      { key: "originalPrice", label: "通常価格", type: "text", required: false, placeholder: "¥9,800", maxLength: 10 },
      { key: "salePrice", label: "セール価格", type: "text", required: false, placeholder: "¥2,980", maxLength: 10 },
      { key: "deadline", label: "期限", type: "text", required: true, placeholder: "3日間限定", maxLength: 10 },
      { key: "ctaText", label: "CTAテキスト", type: "text", required: true, placeholder: "今すぐ購入", maxLength: 15, defaultValue: "今すぐ購入" },
    ],
  },
  "03": {
    id: "03",
    name: "アプリ紹介",
    nameEn: "App Introduction",
    description: "アプリのダウンロードを促進するためのテンプレート",
    category: "アプリ",
    sceneCount: 5,
    fields: [
      { key: "appName", label: "アプリ名", type: "text", required: true, placeholder: "MyApp", maxLength: 20 },
      { key: "problemText", label: "こんな悩みありませんか？", type: "text", required: true, placeholder: "毎日の家計管理が面倒...", maxLength: 30 },
      { key: "screenshotImage", label: "アプリ画面", type: "image", required: false },
      { key: "feature1", label: "機能1", type: "text", required: true, placeholder: "ワンタップで記録", maxLength: 20 },
      { key: "feature2", label: "機能2", type: "text", required: true, placeholder: "自動カテゴリ分類", maxLength: 20 },
      { key: "downloadCount", label: "DL数", type: "text", required: false, placeholder: "100万DL突破", maxLength: 15 },
      { key: "ctaText", label: "CTAテキスト", type: "text", required: true, placeholder: "無料ダウンロード", maxLength: 15, defaultValue: "無料ダウンロード" },
    ],
  },
  "04": {
    id: "04",
    name: "ビフォーアフター",
    nameEn: "Before & After",
    description: "使用前後の変化を劇的に見せるテンプレート",
    category: "比較",
    sceneCount: 5,
    fields: [
      { key: "beforeImage", label: "Before画像", type: "image", required: false },
      { key: "afterImage", label: "After画像", type: "image", required: false },
      { key: "beforeText", label: "Beforeテキスト", type: "text", required: true, placeholder: "導入前", maxLength: 15 },
      { key: "afterText", label: "Afterテキスト", type: "text", required: true, placeholder: "導入後", maxLength: 15 },
      { key: "metricBefore", label: "数値Before", type: "text", required: false, placeholder: "作業時間 8時間", maxLength: 15 },
      { key: "metricAfter", label: "数値After", type: "text", required: false, placeholder: "作業時間 1時間", maxLength: 15 },
      { key: "ctaText", label: "CTAテキスト", type: "text", required: true, placeholder: "詳しくはこちら", maxLength: 15, defaultValue: "詳しくはこちら" },
    ],
  },
  "05": {
    id: "05",
    name: "問題提起→解決型",
    nameEn: "Problem to Solution",
    description: "課題を提示し、解決策として商品・サービスを訴求するテンプレート",
    category: "訴求",
    sceneCount: 5,
    fields: [
      { key: "images", label: "素材画像", type: "images", required: false, maxImages: 2 },
      { key: "problemText", label: "問題提起", type: "text", required: true, placeholder: "こんなお悩みありませんか？", maxLength: 25 },
      { key: "painPoint", label: "痛みのポイント", type: "text", required: true, placeholder: "毎月の経費精算に3時間...", maxLength: 30 },
      { key: "solutionText", label: "解決策", type: "text", required: true, placeholder: "AIが自動で経費処理", maxLength: 25 },
      { key: "howItWorks", label: "使い方", type: "text", required: true, placeholder: "レシートを撮るだけ", maxLength: 20 },
      { key: "benefitStat", label: "効果数値", type: "text", required: false, placeholder: "作業時間90%削減", maxLength: 15 },
      { key: "ctaText", label: "CTAテキスト", type: "text", required: true, placeholder: "無料で試す", maxLength: 15, defaultValue: "無料で試す" },
    ],
  },
  "06": {
    id: "06",
    name: "テスティモニアル（口コミ）",
    nameEn: "Testimonial",
    description: "ユーザーの口コミ・レビューで信頼性を訴求するテンプレート",
    category: "口コミ",
    sceneCount: 5,
    fields: [
      { key: "images", label: "素材画像", type: "images", required: false, maxImages: 2 },
      { key: "review1", label: "口コミ1", type: "textarea", required: true, placeholder: "使い始めて1ヶ月で効果を実感しました", maxLength: 50 },
      { key: "reviewer1", label: "投稿者1", type: "text", required: true, placeholder: "30代 女性", maxLength: 15 },
      { key: "review2", label: "口コミ2", type: "textarea", required: true, placeholder: "コスパ最高です！もう手放せません", maxLength: 50 },
      { key: "reviewer2", label: "投稿者2", type: "text", required: true, placeholder: "40代 男性", maxLength: 15 },
      { key: "rating", label: "総合評価", type: "text", required: true, placeholder: "4.8", maxLength: 5, defaultValue: "4.8" },
      { key: "totalReviews", label: "レビュー件数", type: "text", required: false, placeholder: "1,200件", maxLength: 10 },
      { key: "ctaText", label: "CTAテキスト", type: "text", required: true, placeholder: "口コミを見る", maxLength: 15, defaultValue: "口コミを見る" },
    ],
  },
  "07": {
    id: "07",
    name: "ランキング・比較",
    nameEn: "Ranking",
    description: "ランキング形式で商品の優位性をアピールするテンプレート",
    category: "比較",
    sceneCount: 5,
    fields: [
      { key: "images", label: "商品画像", type: "images", required: false, maxImages: 3 },
      { key: "category", label: "カテゴリ", type: "text", required: true, placeholder: "人気スキンケア", maxLength: 15 },
      { key: "rank3Name", label: "3位 名前", type: "text", required: true, placeholder: "商品C", maxLength: 15 },
      { key: "rank3Desc", label: "3位 説明", type: "text", required: true, placeholder: "コスパ◎", maxLength: 20 },
      { key: "rank2Name", label: "2位 名前", type: "text", required: true, placeholder: "商品B", maxLength: 15 },
      { key: "rank2Desc", label: "2位 説明", type: "text", required: true, placeholder: "成分充実", maxLength: 20 },
      { key: "rank1Name", label: "1位 名前", type: "text", required: true, placeholder: "自社商品A", maxLength: 15 },
      { key: "rank1Desc", label: "1位 説明", type: "text", required: true, placeholder: "総合力No.1", maxLength: 20 },
      { key: "ctaText", label: "CTAテキスト", type: "text", required: true, placeholder: "1位の理由を見る", maxLength: 15, defaultValue: "詳しくはこちら" },
    ],
  },
  "08": {
    id: "08",
    name: "ストーリーテリング",
    nameEn: "Storytelling",
    description: "主人公の物語を通じて共感を生む感情訴求型テンプレート",
    category: "ストーリー",
    sceneCount: 5,
    fields: [
      { key: "images", label: "ストーリー画像", type: "images", required: false, maxImages: 4 },
      { key: "characterDesc", label: "主人公紹介", type: "text", required: true, placeholder: "忙しい毎日を送るAさん", maxLength: 25 },
      { key: "conflictText", label: "課題", type: "text", required: true, placeholder: "健康が気になり始めて...", maxLength: 25 },
      { key: "journeyText", label: "出会い・行動", type: "text", required: true, placeholder: "そんな時、出会ったのが", maxLength: 25 },
      { key: "resolutionText", label: "解決・変化", type: "text", required: true, placeholder: "3ヶ月で理想の体に", maxLength: 25 },
      { key: "tagline", label: "タグライン", type: "text", required: true, placeholder: "あなたの物語を始めよう", maxLength: 20 },
      { key: "ctaText", label: "CTAテキスト", type: "text", required: true, placeholder: "始めてみる", maxLength: 15, defaultValue: "始めてみる" },
    ],
  },
  "09": {
    id: "09",
    name: "カウントダウン・限定訴求",
    nameEn: "Countdown",
    description: "緊急性と限定感でアクションを促すテンプレート",
    category: "緊急",
    sceneCount: 5,
    fields: [
      { key: "images", label: "素材画像", type: "images", required: false, maxImages: 1 },
      { key: "urgencyHook", label: "緊急フック", type: "text", required: true, placeholder: "【残りわずか】", maxLength: 15 },
      { key: "offerDetail", label: "オファー内容", type: "text", required: true, placeholder: "初回限定50%OFF", maxLength: 20 },
      { key: "deadline", label: "期限表示", type: "text", required: true, placeholder: "24時間", maxLength: 10 },
      { key: "bonusText", label: "特典", type: "text", required: false, placeholder: "さらに送料無料", maxLength: 20 },
      { key: "ctaText", label: "CTAテキスト", type: "text", required: true, placeholder: "今すぐ申し込む", maxLength: 15, defaultValue: "今すぐ申し込む" },
    ],
  },
  "10": {
    id: "10",
    name: "ブランド認知（イメージ重視）",
    nameEn: "Brand Awareness",
    description: "ブランドの世界観を表現し認知を高めるイメージ重視テンプレート",
    category: "ブランド",
    sceneCount: 5,
    fields: [
      { key: "images", label: "ブランド画像", type: "images", required: false, maxImages: 3 },
      { key: "brandVision", label: "ブランドビジョン", type: "text", required: true, placeholder: "未来の暮らしをデザインする", maxLength: 25 },
      { key: "value1", label: "価値観1", type: "text", required: true, placeholder: "Innovation", maxLength: 15 },
      { key: "value2", label: "価値観2", type: "text", required: true, placeholder: "Sustainability", maxLength: 15 },
      { key: "value3", label: "価値観3", type: "text", required: true, placeholder: "Quality", maxLength: 15 },
      { key: "tagline", label: "タグライン", type: "text", required: true, placeholder: "Design Your Tomorrow", maxLength: 25 },
      { key: "ctaText", label: "CTAテキスト", type: "text", required: true, placeholder: "ブランドサイトへ", maxLength: 15, defaultValue: "ブランドサイトへ" },
    ],
  },
};

export const BGM_OPTIONS: BGMOption[] = [
  { id: "bgm-01", name: "コーポレート", file: "audio/bgm/bgm-01-corporate.mp3", mood: "信頼感・落ち着き" },
  { id: "bgm-02", name: "アップビート", file: "audio/bgm/bgm-02-upbeat.mp3", mood: "明るい・前向き" },
  { id: "bgm-03", name: "エモーショナル", file: "audio/bgm/bgm-03-emotional.mp3", mood: "感動・温かみ" },
  { id: "bgm-04", name: "テック", file: "audio/bgm/bgm-04-tech.mp3", mood: "先進的・デジタル" },
  { id: "bgm-05", name: "エレガント", file: "audio/bgm/bgm-05-elegant.mp3", mood: "上品・高級感" },
  { id: "bgm-06", name: "エナジェティック", file: "audio/bgm/bgm-06-energetic.mp3", mood: "活力・スピード" },
  { id: "bgm-07", name: "カーム", file: "audio/bgm/bgm-07-calm.mp3", mood: "穏やか・安心" },
  { id: "bgm-08", name: "ドラマティック", file: "audio/bgm/bgm-08-dramatic.mp3", mood: "緊張感・インパクト" },
  { id: "bgm-09", name: "プレイフル", file: "audio/bgm/bgm-09-playful.mp3", mood: "楽しい・カジュアル" },
  { id: "bgm-10", name: "シネマティック", file: "audio/bgm/bgm-10-cinematic.mp3", mood: "壮大・映画的" },
];

export const TEMPLATE_IDS = Object.keys(TEMPLATE_REGISTRY) as Array<
  keyof typeof TEMPLATE_REGISTRY
>;
